baseURL = "https://www.jobrunr.io/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
languageCode = "en"
title = "JobRunr"
theme = "casper3"
googleAnalytics = "UA-5770953-9"
disableKinds = ["taxonomy"]

[markup.goldmark.renderer]
unsafe= true

[params]
  logo = "jobrunr-logo-white.webp"
  images = ["/blog/2020-04-23-jobrunr-gets-jobs-done.webp"]
  googleAnalyticsID = "G-J3K00HKL9D"
  gtmID = "GTM-MX5H2KM"
  jobRunrVersion = "7.0.0"
  enableTrialButton = false
  enableWebinarPopup = false


[params.twitterCard]
    generate = true
    card = "summary"
    image = "/blog/2020-04-23-jobrunr-gets-jobs-done.webp"
    imageAlt = "JobRunr - get jobs done"
    site = "@jobrunr"
    creator = "@rdehuyss"
    title = "JobRunr"

[languages]
  [languages.en]
    weight = 1
    contentDir = "content/en"
  [languages.ch]
    weight = 3
    contentDir = "content/ch"
  [languages.es]
    weight = 4
    contentDir = "content/es"
  [languages.zh-cn]
    weight = 5
    contentDir = "content/zh-cn"